version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure
    environment:
      - discovery.type=single-node
    networks:
      - elastic-jaeger

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.16
    ports:
      - "14267:14267"
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"
      - "14269:14269"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    command: [
      "--sampling.strategies-file=/usr/strategies.json"
    ]
    volumes: 
      - ./strategies.json:/usr/strategies.json
    restart: on-failure
    networks:
      - elastic-jaeger
    depends_on:
      - elasticsearch

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.16
    ports:
    - "5778:5778"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - COLLECTOR_HOST_PORT=jaeger-collector:14267
    restart: on-failure
    networks:
      - elastic-jaeger
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query:1.16
    ports:
      - "16686:16686"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    restart: on-failure
    networks:
      - elastic-jaeger
    depends_on:
      - jaeger-collector

networks:
  elastic-jaeger:
    driver: bridge 